export const constants = {
  HOURS_IN_A_DAY: 24,
  MINUTES_IN_AN_HOUR: 60,
  SECONDS_IN_A_MINUTE: 60,
  PIXELS_PER_MINUTE: 7,
  MILLISECONDS_IN_A_SECOND: 1000,
  ROW_HEIGHT: 150,
  SCROLL_TIME: 0.2,
  VERTICAL_SCROLL_PIVOT: 4,
  HORIZONTAL_VIEWPORT_SCROLL: 1250,
  HOURS_IN_A_TIMEFRAME: 3
}
